trigger:
  - main
pr:
  branches:
    include:
      - '*'

variables:
  ROOT: $(Build.SourcesDirectory)
  REPOROOT: $(Build.SourcesDirectory)
  OUTPUTROOT: $(REPOROOT)\out
  NUGET_XMLDOC_MODE: none

  WindowsContainerImage: 'onebranch.azurecr.io/windows/ltsc2019/vse2019:latest'

stages:
  - stage: Build_Stage
    jobs:
      - job: Build_Job
        pool:
          type: windows
        
        variables:
          ob_outputDirectory: '$(REPOROOT)\out'

        steps:
          - task: UseDotNet@2
            continueOnError: true
            inputs:
              packageType: 'sdk'
              useGlobalJson: false
              performMultiLevelLookup: true

          - task: CmdLine@2
            displayName: 'Set BuildNumber'
            inputs:
              script: '$(Build.SourcesDirectory)\.version\version.cmd'
              workingDirectory: '$(Build.SourcesDirectory)'
          
          - task: NuGetToolInstaller@1
            displayName: 'Installing Nuget Tool'
          
          - task: NuGetCommand@2
            displayName: 'Restore Packages'
            inputs:
              command: 'restore'
              includeNugetOrg: true
              restoreSolution: '$(Build.SourcesDirectory)\src\Azure-Migrate.Export.sln'
          
          - task: CmdLine@2
            displayName: 'Build Release'
            inputs:
              script: '$(Build.SourcesDirectory)\.azure-pipelines\scripts\build.cmd'
              workingDirectory: '$(Build.SourcesDirectory)'
          
          - task: CopyFiles@2
            displayName: 'Copy_DLLs_To_AzMigExport'
            inputs:
              SourceFolder: '$(Build.SourcesDirectory)\src\bin\Release\'
              Contents: '**\*.dll'
              TargetFolder: '$(Build.SourcesDirectory)\out\AzMigExport'
              OverWrite: true

          - task: CopyFiles@2
            displayName: 'Copy_EXE_To_AzMigExport'
            inputs:
              SourceFolder: '$(Build.SourcesDirectory)\src\bin\Release\'
              Contents: '**\Azure-Migrate-Export.exe'
              TargetFolder: '$(Build.SourcesDirectory)\out\AzMigExport'
              OverWrite: true

          - task: CopyFiles@2
            displayName: 'Copy_Config_To_AzMigExport'
            inputs:
              SourceFolder: '$(Build.SourcesDirectory)\src\bin\Release\'
              Contents: '**\Azure-Migrate-Export.exe.config'
              TargetFolder: '$(Build.SourcesDirectory)\out\AzMigExport'
              OverWrite: true

          - task: CopyFiles@2
            displayName: 'Copy_Detailed-PBIT_To_AzMigExport'
            inputs:
              SourceFolder: '$(Build.SourcesDirectory)\src\bin\Release\'
              Contents: '**\Azure_Migrate_Export_Detailed.pbit'
              TargetFolder: '$(Build.SourcesDirectory)\out\AzMigExport'
              OverWrite: true

          - task: CopyFiles@2
            displayName: 'Copy_HBC-Lite-PBIT_To_AzMigExport'
            inputs:
              SourceFolder: '$(Build.SourcesDirectory)\src\bin\Release\'
              Contents: '**\Azure_Migrate_Export_HBC-Lite.pbit'
              TargetFolder: '$(Build.SourcesDirectory)\out\AzMigExport'
              OverWrite: true
          
          - task: CopyFiles@2
            displayName: 'Copy_README_To_AzMigExport'
            inputs:
              SourceFolder: '$(Build.SourcesDirectory)\src\bin\Release\'
              Contents: '**\README.txt'
              TargetFolder: '$(Build.SourcesDirectory)\out\AzMigExport'
              OverWrite: true