trigger:
- main
pr:
  branches:
    include:
      - '*'

pool:
  vmImage: 'windows-2019'

variables:
  Solution: '$(Build.SourcesDirectory)\src\Azure-Migrate-Export.sln'
  BuildPlatform: 'Any CPU'
  BuildConfiguration: 'Release'

stages:
  - stage: Build_Stage
    jobs:
      - job: Build_Job
        steps:
        - task: NuGetToolInstaller@1
          displayName: 'Installing NuGet Tool'
        
        - task: NuGetCommand@2
          inputs:
            restoreSolution: '$(Solution)'
        
        - task: VSBuild@1
          inputs:
            solution: '$(Solution)'
            msbuildArgs: '/p:TargetProfile=Cloud'
            platform: '$(BuildPlatform)'
            configuration: '$(BuildConfiguration)'
